Updated workflows

diff --git a/.github/workflows/goreleaser.yml b/.github/workflows/goreleaser.yml
--- a/.github/workflows/goreleaser.yml
+++ b/.github/workflows/goreleaser.yml
@@ -34,11 +34,11 @@ jobs:
 
       - name: tests modules
         run: |
-          go mod vendor
-          if [ ! -z "$(git status --porcelain)" ]; then
-            echo "::error::vendor directory if not synched with go.mod, please run go mod vendor"
-            exit 1
-          fi
+          # go mod vendor
+          # if [ ! -z "$(git status --porcelain)" ]; then
+          #   echo "::error::vendor directory if not synched with go.mod, please run go mod vendor"
+          #   exit 1
+          # fi
 
           go mod tidy
           if [ ! -z "$(git status --porcelain)" ]; then
@@ -48,7 +48,7 @@ jobs:
 
       - name: tests
         run: |
-          go test -v ./...
+          make test
 
       - name: Import GPG key
         id: import_gpg
